### PR TITLE
Fix Cargo file capitalization

### PR DESCRIPTION
**Pull request by freopen**
`Cargo.toml` and `Cargo.lock` normally have capital first letter: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

### CODE REVIEW

**Comment by freopen** [comment]
I've discovered  #76 but it seems that the bug is already fixed and the change I propose works properly on my VSCode

**Comment by antfu** [comment]
Does the lower case config work for you? If so I think we could keep all of them lowercase for consistantency.

**Comment by freopen** [comment]
It only works for me when both `Cargo.toml` and `Cargo.lock` are with the capital first letter. Otherwise files are not nested.

**Comment by antfu** [comment]
Should be fixed by #177, thanks!

**Pull request closed without merging**
